monolog:
  channels:
    - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
    - svclog

when@dev:
  monolog:
    handlers:
      main:
        type: rotating_file
        path: "%kernel.logs_dir%/%kernel.environment%.log"
        level: info
        channels: ["!event"]
        # max number of log files to keep
        # defaults to zero, which means infinite files
        max_files: 10
      symfony_server_log:
        type: stream
        level: warning
        channels: ["!event"]
        path: php://stderr
      deprecation:
        type: stream
        channels: [deprecation]
        path: php://stderr
      console:
        type: console
        process_psr_3_messages: false
        channels: ["!event", "!doctrine", "!console"]
      deduplicated:
        type: deduplication
        level: error
        channels: [svclog]
        # the time in seconds during which duplicate entries are discarded (default: 60)
        # time: 60
        handler: symfony_mailer
      urgent:
        type: fingers_crossed
        action_level: error
        channels: ["!svclog"]
        handler: symfony_mailer
        excluded_http_codes: [404, 405]
        buffer_size: 10 # How many messages should be saved? Prevent memory leaks
      symfony_mailer:
        type: symfony_mailer
        from_email: "technik@seli.li"
        to_email: "technik@seli.li"
        subject: "(seli.li dev) An Error Occurred! %%message%%"
        level: error
        formatter: monolog.formatter.html
        content_type: text/html

when@test:
  monolog:
    handlers:
      main:
        type: fingers_crossed
        action_level: error
        handler: nested
        excluded_http_codes: [404, 405]
        channels: ["!event"]
      nested:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%.log"
        level: debug

when@prod:
  monolog:
    handlers:
      main:
        type: rotating_file
        path: "%kernel.logs_dir%/%kernel.environment%.log"
        level: warning
        channels: ["!event"]
        # max number of log files to keep
        # defaults to zero, which means infinite files
        max_files: 21
      console:
        type: console
        process_psr_3_messages: false
        channels: ["!event", "!doctrine", "!console"]
      deduplicated:
        type: deduplication
        level: error
        channels: [svclog]
        # the time in seconds during which duplicate entries are discarded (default: 60)
        # time: 60
        handler: symfony_mailer
      urgent:
        type: fingers_crossed
        action_level: error
        channels: ["!svclog"]
        handler: symfony_mailer
        excluded_http_codes: [404, 405]
        buffer_size: 10 # How many messages should be saved? Prevent memory leaks
      symfony_mailer:
        type: symfony_mailer
        from_email: "technik@seli.li"
        to_email: "technik@seli.li"
        subject: "(seli.li prod) An Error Occurred! %%message%%"
        level: error
        formatter: monolog.formatter.html
        content_type: text/html
