#when@dev:
#    sentry:
#        dsn: '%env(SENTRY_DSN)%'
#        options:
#            release: seli.li@1.2.5
when@prod:
    sentry:
        dsn: '%env(SENTRY_DSN)%'
        options:
            release: seli.li@1.2.5
