when@dev:
    svc_versioning:
        # should git checkin and push runs? Have to be configured first.
        run_git: true
        # should easycorp/easy-deploy-bundle runs? Have to be installed and configured first.
        run_deploy: true
        # run this command before start versioning, stop on error (e.q. phpstan, tests, ...)'
        pre_command: composer run-script phpstan
        # Create a new release in config/packages/sentry.yaml
        create_sentry_release: true
        # Sentry application name (included in release)
        sentry_app_name: seli.li
