svc_log:
    # Minimal log level, see documentation for values
    min_log_level:        1

    # Should the ip address recorded? Please set to true only if this is allowed in your environment (personal data...)
    enable_ip_saving:     true

    # Do you like different source types?
    enable_source_type:   true

    # Class of your one data provider to get info about sourceType and sourceID, see documentation
    data_provider: App\Service\LogDataProvider

    # Should the user id and name recorded? Please set to true only if this is allowed in your environment (personal data...)
    enable_user_saving: true

    # Need the user the role ROLE_ADMIN for viewing logs (default yes)
    need_admin_for_view:  true

    # Need the user the role ROLE_ADMIN for get statistics (default yes)
    need_admin_for_stats: false

when@prod:
    svc_log:
        # Minimal log level
        min_log_level:        2 # Info
